version: "3.9"
services:
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.2"
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"

  web:
    container_name: "crud-fs-es-app"
    build: .
    volumes:
      - .:/usr/src/app/
      - /var/www/:/var/www/
    ports:
      - "5000:5000"
    depends_on:
      - "elastic"
    links:
      - "elastic"


